import Head from 'next/head'
import Image from 'next/image'
import Header from '../component/Header'
import styles from '../styles/Home.module.css'
import commonStyles from "../styles/common.module.css"
import Link from 'next/link'
import { useState } from 'react'

export default function Home({ result, jsonResult }) {
  const [listNames,setListNames] = useState(jsonResult);
  const [name, setName] = useState("")

  const addPost = async () => {
    const random = Math.floor(Math.random() * 1000)
    const parsedData = {
      id: random,
      title: name,
      author: name
    }
    const postingResponse = await fetch("http://localhost:3001/posts", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(parsedData)
    })
    const result = await postingResponse.json()
    console.log("result",result);
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={commonStyles.flex}>      {result.products.map(item => <Link href={`/product/${item.id}`}  > <Image src={item.thumbnail} alt={item.title} width={200} height={200} /></Link>
      )}</div>

      <div>
        {listNames.map(item => <li>{item.title}</li>)}
      </div>
      <input type="text" value={name} onChange={(e) => setName(e.target.value)} />
      <button onClick={addPost}>add new post</button>


      {/* <Header  result={result}/> */}


    </div>
  )
}

// Home.getInitialProps = async (ctx) => {
//   const response = await fetch('https://dummyjson.com/products')
//   const result = await response.json()
//   return {
//     result: result
//   }
// }

// export async function getStaticProps(ctx) {
//   const response = await fetch('https://dummyjson.com/products')
//   const result = await response.json()

//   const jsonResponse = await fetch("http://localhost:3001/posts")
//   const jsonResult = await jsonResponse.json()
//   console.log(jsonResult);

//   return {
//     props: {
//       result: result,
//       jsonResult: jsonResult
//     },
//     revalidate: 10,
//   }
// }

export async function getServerSideProps() {
  const response = await fetch('https://dummyjson.com/products')
  const result = await response.json()

  const jsonResponse = await fetch("http://localhost:3001/posts")
  const jsonResult = await jsonResponse.json()
  console.log("jsonResult");

  return {
    props: {
      result: result,
      jsonResult: jsonResult
    },

  }
}
